### ISSUE TITLE
Missing Library "LibBabble-SubZone-3.0"

### ISSUE THREAD

**Issue by fubaWoW** [The-Sickness/Incoming-BG#10]
```LUA
1x IncCallout/map.lua:5: Cannot find a library instance of "LibBabble-SubZone-3.0".
[string "=[C]"]: in function `error'
[string "@PetTracker/libs/LibStub/LibStub.lua"]:23: in function `LibStub'
[string "@IncCallout/map.lua"]:5: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "LibBabble-SubZone-3.0"."

```

**Comment by The-Sickness** [comment]
I'll look into it once I get home.

**Comment by The-Sickness** [comment]
You need to update to the latest release. LibBabble-SubZone-3.0 was removed awhile back.

**Comment by fubaWoW** [comment]
Im at the latest version "Nov 23, 2024" from Curseforge, downloaded with WowUp



![image](https://github.com/user-attachments/assets/5142bf42-ed65-4924-87ff-3c80ce1d8860)

Error on Login:
```LUA
1x IncCallout/map.lua:5: Cannot find a library instance of "LibBabble-SubZone-3.0".
[string "=[C]"]: in function `error'
[string "@PetTracker/libs/LibStub/LibStub.lua"]:23: in function `LibStub'
[string "@IncCallout/map.lua"]:5: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "LibBabble-SubZone-3.0"."
```

Maybe you removed the Lib itself but not all code related to it as you can clearly see in your file ``..\Interface\AddOns\IncCallout\map.lua`` at ``line 5``

![image](https://github.com/user-attachments/assets/0d8f7179-6cd6-405f-85cb-43737a34ca1e)

**Comment by The-Sickness** [comment]
All fixed. I was running a newer version that what is on Curse. Thanks for the heads up...
