### ISSUE TITLE
BUG & REQUEST: buttons have no format

### ISSUE THREAD

**Issue by zandadoum** [The-Sickness/Incoming-BG#5]
Hello,

BUGS

i had the original incoming addon, which worked for years. i removed it, removed the savedvariables and installed this one.

1) i have a problem with the design, picture: https://imgur.com/j6ap6p6

the buttons have no format, no design. the outside border not either. when you press a button, the pressed down version does have correct format

2) the /inc command doesn't do anything. i have to use the minimap icon (chocolatebar icon actually)

FEATURE REQUESTS:

i have a few ideas or suggestions:

- make the "show on load" optional. i don't pvp often, but everytime i reload i get the mod showing
- option to auto load addon when entering battlegrounds
- option to auto open zone map (its like a small tactical minimap) when opening the inc window

thank you

**Comment by The-Sickness** [comment]
The design will stay as is for now. The original code had like 9 different files and I condensed them down to one. Yes, I'm aware that the color red shows when you click a button, but it does not affect the way it works. I'm considering removing the auto load on login and on a /reload. I see where that mat be an issue. I am also going to fix the /inc command.

**Comment by The-Sickness** [comment]
/inc is now working. GUI will not appear on login or on a /reload.

**Comment by The-Sickness** [comment]
[zandadoum](https://github.com/zandadoum) The red that was under the button color is now gone. All of your other request have been done.

**Comment by zandadoum** [comment]
thank you!

**Comment by The-Sickness** [comment]
[zandadoum](https://github.com/zandadoum) I'm looking into the map request. Kinda held back due to the API. I think I can do it if I resize it. Stay tuned for that.....

**Comment by zandadoum** [comment]
hm, not sure if i explained it properly. that map already exists in the game. i think the default keybind is shift+m

all i was suggesting is to open that one when joining a BG (well, optional ofc, not everyone wants that) to save 1 button press ;)

**Comment by The-Sickness** [comment]
I'm thinking of making a "map" button that will pull up the pvp map, but marking all of your teammates with markers and such. Like I said, there are some API restictions. But I am looking into it.
