### ISSUE TITLE
Feature Request: Disable Map Positioning Override

### ISSUE THREAD

**Issue by ModeratelyAverage** [The-Sickness/Incoming-BG#9]
When this addon is enabled the map frame is centered on the screen, which I find undesirable and frustrating. Please add an option for this so that I can keep the addon enabled and have the map in the default UI position.

**Comment by The-Sickness** [comment]
When you use the map and move it it will remember the position the next time you use it. IF, that doesn't work let me know. But ALL the frames are moveable and their positions are saved in saved variables.

**Comment by ModeratelyAverage** [comment]
That's helpful information. Looks like there is an interaction with the frame movers in the Windtools plugin for ElvUI. Disabling that lets Incoming-BG take over, which is fine because all I ever really need to move is the map anyway.
